In [4]:
import pandas as pd

In [10]:
df=pd.read_csv("Data files/StudentPerformance.csv")

In [11]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74.0
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,NaN
996,male,group C,high school,free/reduced,none,62,55,55.0
997,female,group C,high school,free/reduced,completed,59,71,65.0
998,female,group D,some college,standard,completed,68,78,77.0
999,female,group D,some college,free/reduced,none,77,86,86.0

In [13]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                      0
reading score                   0
writing score                  18
dtype: int64

In [15]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000     982.000000
mean     66.08900      69.169000      67.967413
std      15.16308      14.600192      15.188082
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.250000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [16]:
df.size

8000

In [17]:
df.ndim

2

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                982 non-null    float64
dtypes: float64(1), int64(2), str(5)
memory usage: 62.6 KB

In [19]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74.0
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
994,male,group A,high school,standard,none,63,63,62.0
996,male,group C,high school,free/reduced,none,62,55,55.0
997,female,group C,high school,free/reduced,completed,59,71,65.0
998,female,group D,some college,standard,completed,68,78,77.0
999,female,group D,some college,free/reduced,none,77,86,86.0

In [20]:
df["writing score"]=df["writing score"].astype(float)

In [21]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74.0
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,NaN
996,male,group C,high school,free/reduced,none,62,55,55.0
997,female,group C,high school,free/reduced,completed,59,71,65.0
998,female,group D,some college,standard,completed,68,78,77.0
999,female,group D,some college,free/reduced,none,77,86,86.0

In [22]:
df=df.dropna()

In [23]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74.0
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
994,male,group A,high school,standard,none,63,63,62.0
996,male,group C,high school,free/reduced,none,62,55,55.0
997,female,group C,high school,free/reduced,completed,59,71,65.0
998,female,group D,some college,standard,completed,68,78,77.0
999,female,group D,some college,free/reduced,none,77,86,86.0

In [24]:
df["gender"]=df["gender"].replace({"female":0,"male":1})

In [25]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,group B,bachelor's degree,standard,none,72,72,74.0
1,0,group C,some college,standard,completed,69,90,88.0
2,0,group B,master's degree,standard,none,90,95,93.0
3,1,group A,associate's degree,free/reduced,none,47,57,44.0
4,1,group C,some college,standard,none,76,78,75.0
...,...,...,...,...,...,...,...,...
994,1,group A,high school,standard,none,63,63,62.0
996,1,group C,high school,free/reduced,none,62,55,55.0
997,0,group C,high school,free/reduced,completed,59,71,65.0
998,0,group D,some college,standard,completed,68,78,77.0
999,0,group D,some college,free/reduced,none,77,86,86.0